/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"], // ajusta según tu proyecto
  theme: {
    extend: {
      colors: {
        "surface-tint": "#005bc1",
        "secondary-container": "#dfdfe4",
        "on-primary-container": "#fefcff",
        "primary-container": "#0070eb",
        "on-secondary-container": "#616267",
        "inverse-on-surface": "#eef0fc",
        "tertiary-fixed": "#72fe88",
        "inverse-surface": "#2d3039",
        "on-surface": "#181c23",
        "outline": "#717786",
        "background": "#f9f9ff",
        "surface-container-high": "#e6e8f3",
        "surface-bright": "#f9f9ff",
        "primary": "#0058bc",
        "surface-variant": "#e0e2ed",
        "surface-dim": "#d8d9e5",
        "on-primary-fixed-variant": "#004493",
        "on-tertiary-container": "#f7fff2",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-low": "#f1f3fe",
        "outline-variant": "#c1c6d7",
        "tertiary-container": "#008733",
        "on-secondary-fixed": "#1a1c1f",
        "on-error-container": "#93000a",
        "primary-fixed": "#d8e2ff",
        "tertiary": "#006b27",
        "on-tertiary-fixed-variant": "#00531c",
        "on-background": "#181c23",
        "on-tertiary-fixed": "#002107",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#45474b",
        "inverse-primary": "#adc6ff",
        "tertiary-fixed-dim": "#53e16f",
        "on-surface-variant": "#414755",
        "surface": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c6c6cb",
        "surface-container-highest": "#e0e2ed",
        "surface-container": "#ecedf9",
        "on-primary-fixed": "#001a41",
        "secondary": "#5d5e63",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#adc6ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        "margin-mobile": "16px",
        "gutter-mobile": "12px",
        sm: "12px",
        xs: "4px",
        md: "16px",
        base: "8px",
        lg: "24px",
      },
      fontFamily: {
        h3: ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        h1: ["Inter"],
        button: ["Inter"],
        h2: ["Inter"],
        "label-caps": ["Inter"],
      },
      fontSize: {
        h3: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        h1: ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        button: ["16px", { lineHeight: "20px", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
